export const PricingSectionData = [
    {
        id: "1",
        PricingCartIcon: require('../../img/pricing-plan-icon1.png'),
        PricingCartPricingLevel: "Beginner",
        PricingCartPricingRate: "Free",
        PricingCartPricingRateMonth: "/Month",
        PricingCartText1: "30 Days Product Testing",
        PricingCartText2: "Upgrade Anytime Protection",
        PricingCartText3: "500 Malware Removal",
        PricingCartText4: "24/7 Live Assistance",
        PricingCartText5: "Scan Every 12 Hrs",
        PricingCartText6: "Configure Software One-time",
    },
    {
        id: "2",
        PricingCartIcon: require('../../img/pricing-plan-icon2.png'),
        PricingCartPricingLevel: "Business",
        PricingCartPricingRate: "$39.99",
        PricingCartPricingRateMonth: "/Month",
        PricingCartText1: "40 Days Product Testing",
        PricingCartText2: "Upgrade Anytime Protection",
        PricingCartText3: "1000 Malware Removal",
        PricingCartText4: "24/7 Live Assistance",
        PricingCartText5: "Scan Every 13 Hrs",
        PricingCartText6: "Configure Software One-time",
    },
    {
        id: "3",
        PricingCartIcon: require('../../img/pricing-plan-icon3.png'),
        PricingCartPricingLevel: "Exclusive",
        PricingCartPricingRate: "$47.85",
        PricingCartPricingRateMonth: "/Month",
        PricingCartText1: "50 Days Product Testing",
        PricingCartText2: "Upgrade Anytime Protection",
        PricingCartText3: "Unlimited Malware Removal",
        PricingCartText4: "24/7 Live Assistance",
        PricingCartText5: "Scan Every 14 Hrs",
        PricingCartText6: "Configure Software One-time",
    },
]