export const TeamSectionData = [
    {
        id: "1",
        TeamSectionCartImage: require('../../img/team-img1.jpg'),
        TeamSectionCartCreatorName: "Eric T. Parker",
        TeamSectionCartProfession: "Network Security",
        TeamSectionCartDescription: "Lonec pede justo, fringilla vel, aliquet nec vulputate eget arcu.",
        TeamCart_Instagram: "https://www.instagram.com/_saad_ali_02/",
        TeamCart_Facebook: "https://web.facebook.com/zain.mateen.509",
        TeamCart_Twitter: "https://twitter.com/ZainMateen_259",
    },
    {
        id: "2",
        TeamSectionCartImage: require('../../img/team-img2.jpg'),
        TeamSectionCartCreatorName: "Shira Rubinoff",
        TeamSectionCartProfession: "Security Executive",
        TeamSectionCartDescription: "Lonec pede justo, fringilla vel, aliquet nec vulputate eget arcu.",
        TeamCart_Instagram: "https://www.instagram.com/_saad_ali_02/",
        TeamCart_Facebook: "https://web.facebook.com/zain.mateen.509",
        TeamCart_Twitter: "https://twitter.com/ZainMateen_259",
    },
    {
        id: "3",
        TeamSectionCartImage: require('../../img/team-img3.jpg'),
        TeamSectionCartCreatorName: "Steve Morgan",
        TeamSectionCartProfession: "Security Technologist",
        TeamSectionCartDescription: "Lonec pede justo, fringilla vel, aliquet nec vulputate eget arcu.",
        TeamCart_Instagram: "https://www.instagram.com/_saad_ali_02/",
        TeamCart_Facebook: "https://web.facebook.com/zain.mateen.509",
        TeamCart_Twitter: "https://twitter.com/ZainMateen_259",
    },
]